apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.phpmyadminAppName }}-ingress"
  namespace: {{ .Values.nameSpace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2 
    # The $2 in this rewrite refers to the second capturing group from the regex, which is (.*). 
    # This group captures whatever comes after /phpmyadmin. If nothing follows, $2 will be empty, 
    # meaning a request to /phpmyadmin/ will be rewritten to /, effectively serving the phpMyAdmin root.
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - host: {{ .Values.nodeBalancerPublicDns }}
    http:
      paths:
        - path: {{ .Values.phpmyadminIngressPath }}
        # This RegEx matches either:
        # A trailing slash (/) after /phpmyadmin, or
        # (.*) is a capturing group that matches any remaining part of the URL such as index.html
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ .Values.phpmyadminAppName }}
              port:
                number: {{ .Values.phpmyadminContainerPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.javaAppName }}-ingress"
  namespace: {{ .Values.nameSpace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - host: {{ .Values.nodeBalancerPublicDns }}
    http:
      paths:
        - path: {{ .Values.javaIngressPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.javaAppName }}
              port:
                number: {{ .Values.javaContainerPort }}