apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysqlAppName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.mysqlAppName }}
    app.kubernetes.io/name: {{ .Values.mysqlAppName }}
data:
  primary.cnf: |
{{ .Values.mysqlConfig.primary | indent 4 }}
  replica.cnf: |
{{ .Values.mysqlConfig.replica | indent 4 }}