apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysqlAppName }}
  namespace: exercises
  labels:
    app: {{ .Values.mysqlAppName }}
spec:
  replicas: {{ .Values.mysqlReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mysqlAppName }}
  serviceName: {{ .Values.mysqlAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysqlAppName }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      initContainers:
      - name: "init-{{ .Values.mysqlAppName }}"
        image: {{ .Values.mysqlImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
        - bash
        - "-c"
        - {{- toYaml .Values.mysqlInitCommand | nindent 8 }}
        {{- with .Values.mysqlInitVolumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      - name: "clone-{{ .Values.mysqlAppName }}"
        image: {{ .Values.xtrabackupImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
        - bash
        - "-c"
        - {{- toYaml .Values.xtrabackupCloneCommand | nindent 8 }}
        {{- with .Values.xtrabackupCloneVolumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - name: {{ .Values.mysqlAppName }}
        image: {{ .Values.mysqlImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        envFrom:
        - secretRef:
            name: {{ .Values.javaMysqlEnvSecret }}
        ports:
        - name: {{ .Values.mysqlAppName }}
          containerPort: {{ .Values.mysqlContainerPort }}
        {{- with .Values.mysqlVolumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.cpuRequestedMysql }}
            memory: {{ .Values.memoryRequestedMysql }}
          limits:
            cpu: {{ .Values.cpuLimitMysql }}
            memory: {{ .Values.memoryLimitMysql }}
        livenessProbe:
          exec:
            command: {{ .Values.mysqlLivenessProbeCommand  |  toJson }}
          initialDelaySeconds: {{ add .Values.livenessProbeInitialDelay 25 }}
          periodSeconds: {{ add .Values.livenessProbePeriod 5 }}
          timeoutSeconds: {{ .Values.livenessProbeTimeoutSeconds }}
        readinessProbe:
          exec:
            command: {{ .Values.mysqlReadinessProbeCommand  | toJson }}
          initialDelaySeconds: {{ .Values.readinessProbeInitialDelay }}
          periodSeconds: {{ sub .Values.readinessProbePeriod 3 }}
          timeoutSeconds: {{ sub .Values.readinessProbeTimeoutSeconds 4 }}
      - name: {{ .Values.xtrabackupAppName }}
        image: {{ .Values.xtrabackupImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: {{ .Values.xtrabackupAppName }}
          containerPort: {{ .Values.xtrabackupContainerPort }}
        envFrom:
        - secretRef:
            name: {{ .Values.javaMysqlEnvSecret }}
        command:
        - bash
        - "-c"
        - {{- toYaml .Values.xtrabackupBashCmd | nindent 8 }}
        {{- with .Values.xtrabackupVolumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.cpuRequested }}
            memory: {{ .Values.memoryRequested }}
          limits:
            cpu: {{ .Values.cpuLimit }}
            memory: {{ .Values.memoryLimit }}
      {{- with .Values.mysqlVolumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- with .Values.mysqlVolumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 2 }}
  {{- end }}