# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlAppName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.mysqlAppName }}
spec:
  ports:
  - name: {{ .Values.mysqlAppName }}
    port: {{ .Values.mysqlContainerPort }}
  clusterIP: None
  selector:
    app: {{ .Values.mysqlAppName }}
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql
# P.S. sometimes writes can be possible through mysql-read service if it chooses the root replica at random!
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.mysqlAppName }}-read"
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.mysqlAppName }}
    readonly: "true"
spec:
  selector:
    app: {{ .Values.mysqlAppName }}
  ports:
  - name: {{ .Values.mysqlAppName }}
    port: {{ .Values.mysqlContainerPort }}
