appName: checkoutservice
servicePort: 5050
containerPort: 5050
containerEnvVars:
  - name: PORT
    value: "5050"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: EMAIL_SERVICE_ADDR
    value: "emailservice:8080"
  - name: PAYMENT_SERVICE_ADDR
    value: "paymentservice:50051"
  - name: CURRENCY_SERVICE_ADDR
    value: "currencyservice:7000"
  - name: SHIPPING_SERVICE_ADDR
    value: "shippingservice:50051"
  - name: CART_SERVICE_ADDR
    value: "cartservice:7070"
#cpuRequested: 100m
#memoryRequested: 64Mi
#cpuLimit: 200m
#memoryLimit: 128Mi

#readinessProbeInitialDelay: 5
#readinessProbePeriod: 5
#livenessProbeInitialDelay: 5
#livenessProbePeriod: 5