appName: currencyservice
servicePort: 7000
containerPort: 7000
containerEnvVars:
  - name: PORT
    value: "7000"
  - name: DISABLE_PROFILER
    value: "1"

#cpuRequested: 100m
#memoryRequested: 64Mi
#cpuLimit: 200m
#memoryLimit: 128Mi

#readinessProbeInitialDelay: 5
#readinessProbePeriod: 5
#livenessProbeInitialDelay: 5
#livenessProbePeriod: 5