appName: recommendationservice
servicePort: 8080
containerPort: 8080
containerEnvVars:
  - name: PORT
    value: "8080"
  - name: DISABLE_PROFILER
    value: "1"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
#cpuRequested: 100m
memoryRequested: 220Mi
#cpuLimit: 200m
memoryLimit: 450Mi

#readinessProbeInitialDelay: 5
#readinessProbePeriod: 5
#livenessProbeInitialDelay: 5
#livenessProbePeriod: 5