services:
  node-app:
    image: ${AWS_NODE_IMG_URL}
    container_name: node-app
    ports:
     - 3000:3000
    networks:
      - node-mongo-bridge
    env_file:
      - app/.env
    environment:
      - NODE_ENVIRONMENT=docker-development

  mongodb:
    image: mongo:7.0.14
    container_name: mongodb
    networks:
      - node-mongo-bridge
    ports:
     - 27017:27017
    env_file:
      - app/.env
    volumes:
     - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: always
    networks:
      - node-mongo-bridge
    ports:
     - 8081:8081
    env_file:
      - app/.env
    depends_on:
     - "mongodb"

volumes:
  mongo-data:
    driver: local

networks:
  node-mongo-bridge:
    driver: bridge
