apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: exercises
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      terminationGracePeriodSeconds: 5
      #securityContext:
      #  fsGroup: 1000
      #  runAsGroup: 1000
      #  runAsNonRoot: true
      #  runAsUser: 1000
      containers:
        - name: phpmyadmin
          image: phpmyadmin:5.2.1-apache
          ports:
            - containerPort: 80
          env:
            - name: PMA_ABSOLUTE_URI
              valueFrom:
                configMapKeyRef:
                  name: phpmyadmin-configmap
                  key: pma-absolute-uri
            - name: PMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: phpmyadmin-configmap
                  key: pma-host
            - name: PMA_PORT
              valueFrom:
                configMapKeyRef:
                  name: phpmyadmin-configmap
                  key: pma-port
            - name: PMA_ARBITRARY
              valueFrom:
                configMapKeyRef:
                  name: phpmyadmin-configmap
                  key: pma-arbitrary-server-address
          #securityContext:
          #  allowPrivilegeEscalation: false
          #  capabilities:
          #    drop:
          #      - ALL
          #  privileged: false
          #  readOnlyRootFilesystem: true
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80