apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - image: mysql:9.0.1
        name: mysqldb-container
        envFrom:
        - secretRef:
            name: java-app-mysql-env
        ports:
        - containerPort: 3306
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          #readOnlyRootFilesystem: true
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 768Mi
        volumeMounts:
        - name: mysqldb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysqldb-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: mysqldb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  #clusterIP: None