apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: exercises
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi