apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: exercises
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: phpmyadmin
          image: phpmyadmin:5.2.1-apache
          ports:
            - containerPort: 80
          env:
            - name: PMA_ARBITRARY
              value: "1"
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: exercises
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80